apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: webApp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webApp
  template:
    metadata:
      labels:
        app: webApp
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
