apiVersion: apps/v1
kind: Deployment

metadata:
  name: postgres
  labels:
    app: postgres

spec:
  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
      image: postgres:latest
      ports: 
        - containerPort: 5432
      volumes:
        - name: postgress-volume
      persistentVolumeClaim:
        claimName: dbvolume-claim


      volumeMounts:
        - name: postgress-volume
          mountPath: "/var/lib/postgresql/data"
